### ISSUE TITLE
querystream has missing variables

### ISSUE THREAD

**Issue by yoshuawuyts** [substack/hyperlog-kdb-index#1]
I was reading through the code, and it seems that some values are missing from `HKDB.prototype.queryStream` https://github.com/substack/hyperlog-kdb-index/blob/master/index.js#L80

``` js
HKDB.prototype.queryStream = function (q, opts) {
  var r = through.obj()
  // self is not defined
  self.ready(function () {
    var qs = self.kdb.queryStream(q, opts)
    qs.on('error', r.emit.bind(r, 'error'))
    qs.pipe(r)
  })
  // readonly is not defined
  return readonly(r)
}
```

I'd PR it, but not sure what `readonly` should be. Cheers!

**Comment by noffle** [comment]
This no longer seems to be the case. Thanks yosh!
